class Keys:
    ESCAPE = 'escape'
    DELETE = 'delete'
    ENTER = 'enter'
    BACKSPACE = 'backspace'
    UP = 'up'
    DOWN = 'down'
    LEFT = 'left'
    RIGHT = 'right'
    TAB = 'tab'
    CHAR = 'char'
